// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngzmbjwlldjpbmtsmikq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nem1iandsbGRqcGJtdHNtaWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTIwNDcsImV4cCI6MjA2MDM4ODA0N30.DbDlKU9VTzIeeytuRUdGMHmNWzK9kyHOOwzMyND7eWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);